### ISSUE TITLE
[RPC] - Editor not saving a new source for the EDM asset correctly

### ISSUE THREAD

**Issue by samuelfm** [GAIPS-INESC-ID/FAtiMA-Toolkit#1]

**Comment by Rexrex** [comment]
Our development team is currently working to fix this issue, could you please be more specific when describing the problem?

**Comment by samuelfm** [comment]
The problem occurs when we are trying to use the button "Set" in a new RPC. The bug also happens with the EA assets.

**Comment by Rexrex** [comment]
Here is the fix eb6789e 
Now everytime we select the Set option and chose a file it opens the asset editor immediately
