### ISSUE TITLE
[IAT] - Dialogue Retrieval

### ISSUE THREAD

**Issue by samuelfm** [GAIPS-INESC-ID/FAtiMA-Toolkit#2]
The dialogue editor allows one to specify multiple utterances for the same symbolical meaning. However, the dialogue retrieval mechanism is only returning a single utterance (should return all the utterances).

**Comment by Rexrex** [comment]
I've added a "GetDialogueActions" method to the IAT Asset that returns a list of all the possible dialog options with the specified speaker, current state, next state, meaning and style.

This solution needs to be tested

**Comment by Rexrex** [comment]
This issue should be solved by now, developers need to use the proper method (if they don't an error will appear so...).

This just needs to be transferred to the IAT asset DLL in the FAtiMA Demos repository...
