### ISSUE TITLE
[BUG] LastEventId is not working properly on unity

### ISSUE THREAD

**Issue by samuelfm** [GAIPS-INESC-ID/FAtiMA-Toolkit#20]
This is because it uses a Linq operation (LAST) that Unity does not support

**Comment by Rexrex** [comment]
Updated the Last Event ID method to stop using the .Last() operation. Method now uses a FOR operation to get the latest timestamp and then uses a WHERE(x =>x.Value.Timestamp == lastestTimestamp)
