### ISSUE TITLE
[BUG] - It is not possible to remove a belief from the KB using a property change event

### ISSUE THREAD

**Issue by samuelfm** [GAIPS-INESC-ID/FAtiMA-Toolkit#26]
When perceiving a property change in which the new value is "-" the belief should be removed from the KB.

**Comment by Rexrex** [comment]
Implemented this feature, added a condition to the Perceive Method in the Emotional Appraisal and implemented a RemoveBelief method in the KB. Also added Unit Tests to make sure it works
