### ISSUE TITLE
[Feature] Add a fifth argument to the Speak action that will contain dialogue parameters

### ISSUE THREAD

**Issue by samuelfm** [GAIPS-INESC-ID/FAtiMA-Toolkit#33]
Currently, it is not possible to have utterances with variables inside, which limits the flexibility of the dialogue.

This change aims to fix that by simply adding a fifth argument to the speak action.

So instead of Speak([cs],[ns],[m],[s]) we will have Speak([cs],[ns],[m],[s],[p]) where [p] will be a composed name like "P(John,5)".

Then in the dialogue editor we will define dialogues like this:

Start, S1, Meaning(Greeting, GiveMoney), Polite, "Hi [p1]. Here is the [p2] dollars I borrowed from you."

This dialogue will be selected based on the decision to perform "Speak(Start, S1, Meaning(Greeting, GiveMoney), Polite, P(John, 5))"

**Comment by Rexrex** [comment]
It is now possible to have variables within Utterances using [[variable]] and then using the method Process With Beliefs
