### ISSUE TITLE
[Bug] Integrated Authoring Tool - Decision Making Tab

### ISSUE THREAD

**Issue by hineios** [GAIPS-INESC-ID/FAtiMA-Toolkit#34]
When in small screens the authoring tool does not display the scroll bar even if there are hidden decision rules.

![capture](https://user-images.githubusercontent.com/9935493/36786653-1bd3f4d2-1c7f-11e8-9554-7a76ede28163.PNG)

**Comment by samuelfm** [comment]
This bug was fixed in commit 078a169
