### ISSUE TITLE
Mood Decay Bug

### ISSUE THREAD

**Issue by Rexrex** [GAIPS-INESC-ID/FAtiMA-Toolkit#4]
User Report: 

"I think I may have come across a couple of bugs related to the decaying of moods and emotions.

It seems that _tickT0 is always 0 in the Mood class and that tickATt0 is always 0 upon reloading in the ActiveEmotion class. I've attached some RPC files which I hope help show the issue.

The 'Base' file shows the state of a character just after an event which has affected their mood and emotions, whilst the 'WithReload' and 'WithoutReload' files are 25 ticks later, which is the HalfLifeDecayTime being used."

**Comment by Rexrex** [comment]
This issue has been fixed, the problem was that we were not updating the _tickT0 properly, as the user said it was always 0. It is now updating properly.

**Comment by PipzCorreiaz** [comment]
@Rexrex I think you have left a print somewhere when an emotion is removed.

**Comment by Rexrex** [comment]
@PipzCorreiaz  Yup! Thank you for notifying me! (Fixed)
